"""Add payment_method to orders and remove admins table

Revision ID: 32f5bfea1808
Revises: 9400e67beb41
Create Date: 2025-12-19 22:54:07.665849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32f5bfea1808'
down_revision = '9400e67beb41'
branch_labels = None
depends_on = None


def upgrade():
    # Drop admins table if it exists and add payment_method column idempotently
    op.execute("DROP TABLE IF EXISTS admins")
    op.execute("ALTER TABLE orders ADD COLUMN IF NOT EXISTS payment_method VARCHAR(20)")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('payment_method')

    op.create_table('admins',
    sa.Column('admin_id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=100), nullable=True),
    sa.Column('password_hash', sa.VARCHAR(length=255), nullable=True),
    sa.Column('email', sa.VARCHAR(length=100), nullable=True),
    sa.Column('role', sa.VARCHAR(length=20), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('last_login', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('admin_id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###
