"""Add razorpay_order_id to Order

Revision ID: 9400e67beb41
Revises: 
Create Date: 2025-12-15 13:04:35.477470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9400e67beb41'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # Add columns only if they do not already exist (idempotent for existing DBs)
    op.execute("ALTER TABLE customers ADD COLUMN IF NOT EXISTS password_hash VARCHAR(255)")
    op.execute("ALTER TABLE orders ADD COLUMN IF NOT EXISTS razorpay_order_id VARCHAR(100)")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('razorpay_order_id')

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
