"""Add stock_quantity to menu_items

Revision ID: c4bf34826151
Revises: 32f5bfea1808
Create Date: 2025-12-24 16:00:16.441434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4bf34826151'
down_revision = '32f5bfea1808'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stock_quantity', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu_items', schema=None) as batch_op:
        batch_op.drop_column('stock_quantity')

    # ### end Alembic commands ###
