"""add admin_settings table

Revision ID: fec2bca9c10b
Revises: 8f210e1d574f
Create Date: 2026-02-25 15:50:04.771003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fec2bca9c10b'
down_revision = '8f210e1d574f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('monthly_statistics',
    sa.Column('stat_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('month', sa.Integer(), nullable=True),
    sa.Column('total_orders', sa.Integer(), nullable=True),
    sa.Column('total_revenue', sa.Float(), nullable=True),
    sa.Column('confirmed_orders', sa.Integer(), nullable=True),
    sa.Column('pending_orders', sa.Integer(), nullable=True),
    sa.Column('completed_orders', sa.Integer(), nullable=True),
    sa.Column('cancelled_orders', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('stat_id')
    )
    # NOTE: Skipping automatic conversion of `menu_items.category` to JSON here
    # because existing data may not be valid JSON. Manual migration required
    # if you want to convert existing values. This migration only creates the
    # new `admin_settings` and `monthly_statistics` tables.

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu_items', schema=None) as batch_op:
        batch_op.alter_column('category',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)

    op.drop_table('monthly_statistics')
    op.drop_table('admin_settings')
    # ### end Alembic commands ###
